# See docs at https://conduwuit.puppyirl.gay/configuration.html.
# The install has an example with tons of comments

[global]
server_name = "matrix.polypod.space"
database_path = "/var/www/conduwuit-polypod-data"
database_backend = "rocksdb"
port = 3083
address = ["127.0.0.1", "::1"]
max_request_size = 20_000_000 # in bytes
zstd_compression = false
gzip_compression = false
brotli_compression = false
ip_range_denylist = [
    "127.0.0.0/8",
    "10.0.0.0/8",
    "172.16.0.0/12",
    "192.168.0.0/16",
    "100.64.0.0/10",
    "192.0.0.0/24",
    "169.254.0.0/16",
    "192.88.99.0/24",
    "198.18.0.0/15",
    "192.0.2.0/24",
    "198.51.100.0/24",
    "203.0.113.0/24",
    "224.0.0.0/4",
    "::1/128",
    "fe80::/10",
    "fc00::/7",
    "2001:db8::/32",
    "ff00::/8",
    "fec0::/10",
]

# Enables registration. If set to false, no users can register on this
# server.
# If set to true without a token configured, users can register with no form of 2nd-
# step only if you set
# `yes_i_am_very_very_sure_i_want_an_open_registration_server_prone_to_abuse` to
# true in your config. If you would like
# registration only via token reg, please configure the `registration_token` key.
allow_registration = true
registration_token = "moot-glucose-mystery-brigand"

# we will probably change this when we figure out the right model
allow_federation = false
allow_public_room_directory_without_auth = false

new_user_displayname_suffix = ""

# If you are using delegation via well-known files and you cannot serve them from your reverse proxy, you can
# uncomment these to serve them directly from conduwuit. This requires proxying all requests to conduwuit, not just `/_matrix` to work.
[global.well_known]
server = "matrix.polypod.space:443"
client = "https://matrix.polypod.space"
support_page = "https://github.com/darobin/polypod-people"
#support_role = ""
support_email = "robin@berjon.com"
#support_mxid = ""
